{% set name = "ndim" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndim-{{ version }}.tar.gz
  sha256: 44f7edcc32cc938a392b189fa02ee97d6af9e8b823edeeac627d6c325a5d21a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - importlib-metadata
    - python >=3.5
    - sympy

test:
  imports:
    - ndim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/ndim
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Compute multidimensional volumes and monomial integrals.
  description: |
    ndim computes all kinds of volumes and integrals of monomials over 
    such volumes in a fast, numerically stable way, using recurrence
    relations.
  doc_url: https://github.com/nschloe/ndim
  dev_url: https://github.com/nschloe/ndim

extra:
  recipe-maintainers:
    - jan-janssen
